# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsydoGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ET', 'Eat'), ('DR', 'Drink'), ('PT', 'Party'), ('AD', 'Adventure'), ('EX', 'Explore'), ('WK', 'Work Out'), ('LG', 'Look Good'), ('KD', 'Kids'), ('WT', 'Watch'), ('TR', 'Travel'), ('NW', 'News')], default='ET', max_length=2)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
